### ISSUE TITLE
why not use '>'

### ISSUE THREAD

**Issue by ccccm4** [tarunkant/CTF#1]
clause=!having%0asleep(user()%3E0b1101011);%00

**Comment by tarunkant** [comment]
you could have used `<` and check for last value for which it's not sleeping.
if you see `select sleep(user()<0b0111001001101111);` it is last value for which its not sleeping (It is checking if the user is root). Like that you can find whole string.
but if you do use `>` then you have to check for last sleeping value, which will take much more time.
But at last I wanna say both ways gonna take more time than my way does.
